### ISSUE TITLE
Regression in expression parsing

### ISSUE THREAD

**Issue by Jerrythafast** [trifacta/vega#260]
Dear Vega devs,

In one of my graph specs I have the following filter transform (using dummy names in this example):

```{"type": "filter", "test": "['Jack','James','Jamie'].indexOf(d.data.name)>-1)"}```

Until the recent Vega update, this worked fine. Now, I get

> Error: Illegal callee type: MemberExpression

Of course, I admit this particular expression is just a very lazy shortcut, so it is not so much of a problem for me in this specific case. However, there are plenty of reasons someone could be calling e.g. a string method. I'll give one away:

```{"type": "filter", "test": "d.data.name.lastIndexOf('Ja', 0) === 0"}```

This results in the same error. ~~(I have not tested this expression against an older version of Vega, but I expect it to work fine nonetheless).~~ EDIT: I tested it against an older version now, and it worked as it should before the update.

Therefore, I hope you are able to fix this problem in a future release. There is exactly one commit that could have possibly caused this, but it is a bit too advanced for me to dig into it and fix this myself:
https://github.com/trifacta/vega/commit/e68f7b4d87b290249b61b0f1b4bf5dc769f83086

Yours,
Jerry

**Comment by jheer** [comment]
There were significant changes to the expression parsing infrastructure in v1.5.0. One piece of good news here is that it is now much more secure. However, it is not fully backward-compatible, as the previous parser let you get away with just about anything JavaScript allows.

All common number, string and date functions should be supported but are now invocable only through top-level functions: for example `length('123')` rather than `'123'.length`.

Based on your input, I added the functions `indexof` and `lastindexof`, which are now supported on the v1.5.1 branch. Documentation is still in progress, but in the meantime, you can see all supported functions in the code here: https://github.com/trifacta/vega/blob/v1.5.1/src/expression/functions.js

Hope that helps!

**Comment by Jerrythafast** [comment]
Thanks for the quick response! I can confirm the given examples work as expected now, when rewritten to:

```{"type": "filter", "test": "indexof(['Jack','James','Jamie'], d.data.name) > -1)"}```

```{"type": "filter", "test": "lastindexof(d.data.name, 'Ja', 0) === 0"}```

I must note that the first example works merely because of the inequality `> -1`. The array is now converted to a string `"Jack,James,Jamie"`. This also means that a partial match like `"Jac"` or even `"ck,Ja"` is accepted now. The new expression parser will need explicit support for arrays and probably a separate `indexof` function for arrays to fix this example.

But of course, I will just rewrite the filter into a series of string comparisons for the time being.

Finally, although completely off topic, I would like to say you are delivering great stuff with Vega!

Jerry

**Comment by tonyb1974** [comment]
Hello everybody. Hi @jheer 
I am new to vega and would like to create some text marks based on json object value.
It seems JSON.stringify is not allowed. 
Is there any workaround for this ? Is it possible to add support for it without security break ?
Thanks a lot for your answers, best regards
